### ISSUE TITLE
When transferring a video a broken pipe error occurs.

### ISSUE THREAD

**Issue by chriscn** [sdushantha/qr-filetransfer#19]
Error Log for your connivence:
```
Exception happened during processing of request from ('192.168.113.25', 49767)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/bin/qr-filetransfer", line 37, in do_GET
    super().do_GET()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 844, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```
Was using an MP4 which was downloaded from Youtube as an mkv and then converted using ffmepg.
Maybe a weird issue, have been able to replicate it however. Hope this helps 👍

**Comment by chriscn** [comment]
Just sent you an Email, maybe an odd bug.

**Comment by sdushantha** [comment]
It must be very odd bug. I tested it with the file you sent and it worked perfectly fine. I replied to your email with proof

**Comment by sdushantha** [comment]
Should I close this? I am unable to reproduce this bug.

**Comment by chriscn** [comment]
I'll close it, maybe an odd system configuration my end.

**Comment by 097115** [comment]
Also experience the very same problem with MP4 files. Works fine If zipped or the extension is changed to MKV.

The latest master qr-transfer.py, netifaces 0.11.0, Python 3.9.7, Ubuntu. Clients: iOS 11, iOS 12 (not really the latest ones, yes :)
