### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by duplaja** [sdushantha/qr-filetransfer#31]
OS: Ubuntu 18.04 LTS (Desktop), 64-bit

Error occured with both pip3 and Github install. QR code was generated, but threw this when I tried to download via phone.

192.168.8.137 - - [06/May/2019 20:29:40] "GET /Training-Form.docx HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.8.137', 46964)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "./qr-filetransfer", line 57, in do_GET
    super().do_GET()
  File "/usr/lib/python3.6/http/server.py", line 639, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.6/http/server.py", line 800, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/lib/python3.6/socketserver.py", line 800, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------

**Comment by duplaja** [comment]
On further testing, looks like it depended on the browser I tried opening it with on my phone. Chrome worked just fine. NoChromo did not, so must be a permissions issue there.
