### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by CyberPotat42** [sdushantha/qr-filetransfer#50]
```
Traceback (most recent call last):
  File "C:\Program Files\Python\Scripts\qr-filetransfer-script.py", line 33, in <module>
    sys.exit(load_entry_point('qr-filetransfer==2.7', 'console_scripts', 'qr-filetransfer')())
  File "C:\Program Files\Python\lib\site-packages\qr_filetransfer\qr_filetransfer.py", line 527, in main
    start_download_server(file_path=args.file_path, debug=args.debug, custom_port=args.port, ip_addr=args.ip_addr, auth=args.auth)
  File "C:\Program Files\Python\lib\site-packages\qr_filetransfer\qr_filetransfer.py", line 369, in start_download_server
    SSID = get_ssid()
  File "C:\Program Files\Python\lib\site-packages\qr_filetransfer\qr_filetransfer.py", line 299, in get_ssid
    interface_info = os.popen("netsh.exe wlan show interfaces").read()
  File "C:\Program Files\Python\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 526: character maps to <undefined>
```

This is probably caused by incorrect encoding of the response from `os.popen("netsh.exe wlan show interfaces")` (Russian language)

How fix it: https://stackoverflow.com/a/47781109/15301038

**Comment by CyberPotat42** [comment]
UPD: some more error logs:

executing the command `NetSh WLAN Show interfaces` in the console gives me:  
```
В системе 1 интерфейс:

    Имя:                                Беспроводная сеть
    Описание:                       Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
    Идентификатор GUID:   f3****77-1f16-****-baac-25********bf
    Физический адрес:       80:**:**:**:**:cd
    Состояние:                     Подключено
    SSID: Potato
    BSSID: 78:**:**:**:**:78
    Тип сети:                          Инфраструктура
    Тип радио:                        802.11n
    Проверка подлинности:  WPA2-Personal
    Шифр:                                CCMP
    Режим подключения:      Автоматическое подключение
    Канал:                               11
    Скорость приема (Мбит/с):    144.4
    Скорость передачи (Мбит/с): 144.4
    Сигнал:                                     100%
    Профиль                : *********

    Hosted network status  : Недоступно
```

This is the russian encoding that causes the error UnicodeDecodeError

**Comment by imba-tjd** [comment]
Could you show the result of `chcp` in cmd and `import locale; print(locale.getpreferredencoding())`?

**Comment by potat-dev** [comment]
@imba-tjd sure! Sorry for being so late  
Here is the results:  
```console
C:\WINDOWS\system32>chcp
Текущая кодовая страница: 866
```
and
```console
>>> import locale
>>> print(locale.getpreferredencoding())
cp1251
```

**Comment by imba-tjd** [comment]
Well then I can't figure out why.

I have similar settings as yours, and `netsh` also shows non-English output. But I can run `os.popen("netsh.exe wlan show interfaces").read()`

**Comment by potat-dev** [comment]
I think I found a way to avoid this error  
Using `subprocess.run` I get:  
```console
>>> import subprocess
>>> subprocess.run('netsh.exe wlan show interfaces')

В системе 1 интерфейс:

    Имя:                                Беспроводная сеть
    Описание:                       Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
    Идентификатор GUID:   f3******-****-****-****-**********bf
    ...

    Hosted network status  : Недоступно

CompletedProcess(args='netsh.exe wlan show interfaces', returncode=0)
```

This is exactly what the `netsh.exe wlan show interfaces` displays ([⬆️](https://github.com/sdushantha/qr-filetransfer/issues/50#issuecomment-1035662580))

**Comment by imba-tjd** [comment]
That's not meaningful. You need to see whether `subprocess.run('netsh.exe wlan show interfaces', text=True, capture_output=True).stdout` works. Without those args, the output will bypass python and directly write to console.

**Comment by potat-dev** [comment]
We can avoid all possible Unicode errors just by using this library: `ctypes.windll` to manually change the text encoding in the console
```python
from ctypes import windll

prev_codepage = windll.kernel32.GetConsoleOutputCP()
windll.kernel32.SetConsoleOutputCP(65001)
interface_info = os.popen("netsh.exe wlan show interfaces").read()
windll.kernel32.SetConsoleOutputCP(prev_codepage)
```
